#pragma once

#include <d3d9.h>

typedef enum 
{
	TEXTURE_INDEX_BG,
	TEXTURE_INDEX_TITLE,
	TEXTURE_INDEX_PRESS,
	TEXTURE_INDEX_METER,
	TEXTURE_INDEX_NEEDLE,
	TEXTURE_INDEX_SCORE,
	TEXTURE_INDEX_RESULT,
	TEXTURE_INDEX_FIELD01,
	TEXTURE_INDEX_FIELD03,
	TEXTURE_INDEX_SCORE002,
	TEXTURE_INDEX_SABCD,
	TEXTURE_INDEX_FLAME_L,
	TEXTURE_INDEX_FLAME_S,
	TEXTURE_INDEX_1ST,
	TEXTURE_INDEX_2ND,
	TEXTURE_INDEX_3RD,
	TEXTURE_INDEX_4TH,
	
	TEXTURE_INDEX_PEDAL,
	TEXTURE_INDEX_CH_TUTORIAL,
	TEXTURE_INDEX_YES,
	TEXTURE_INDEX_NO,

	TEXTURE_INDEX_TEMPORARY,//一時的に画像貼りたい時用のやつ
	TEXTURE_INDEX_TEMPORARY2,//一時的に画像貼りたい時用のやつ

	TEXTURE_INDEX_MAX
}TextureIndex;

int Texture_Load(void); //初期化
void Texture_Release(void); //終了処理
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);
int Texture_GetWidth(TextureIndex index);
int Texture_GetHeight(TextureIndex index);
